/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ProductCategory = IDL.Variant({
  'sunscreen' : IDL.Null,
  'toner' : IDL.Null,
  'cleanser' : IDL.Null,
  'other' : IDL.Null,
  'serum' : IDL.Null,
  'moisturizer' : IDL.Null,
});
export const Expense = IDL.Record({
  'date' : Time,
  'productName' : IDL.Text,
  'notes' : IDL.Text,
  'category' : ProductCategory,
  'amount' : IDL.Float64,
});
export const ExpenseId = IDL.Nat;
export const JourneyEntry = IDL.Record({
  'breakoutsCount' : IDL.Nat,
  'hydrationLevel' : IDL.Nat,
  'date' : Time,
  'overallRating' : IDL.Nat,
  'notes' : IDL.Text,
  'skinCondition' : IDL.Text,
});
export const JourneyEntryId = IDL.Nat;
export const Product = IDL.Record({
  'isFinished' : IDL.Bool,
  'purchasePrice' : IDL.Float64,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'category' : ProductCategory,
  'estimatedDays' : IDL.Nat,
  'startDate' : Time,
});
export const ProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpense' : IDL.Func([Expense], [ExpenseId], []),
  'addJourneyEntry' : IDL.Func([JourneyEntry], [JourneyEntryId], []),
  'addProduct' : IDL.Func([Product], [ProductId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExpense' : IDL.Func([ExpenseId], [], []),
  'deleteJourneyEntry' : IDL.Func([JourneyEntryId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllJourneyEntries' : IDL.Func([], [IDL.Vec(JourneyEntry)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpense' : IDL.Func([ExpenseId], [Expense], ['query']),
  'getJourneyEntry' : IDL.Func([JourneyEntryId], [JourneyEntry], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getTotalExpenses' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateExpense' : IDL.Func([ExpenseId, Expense], [], []),
  'updateJourneyEntry' : IDL.Func([JourneyEntryId, JourneyEntry], [], []),
  'updateProduct' : IDL.Func([ProductId, Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ProductCategory = IDL.Variant({
    'sunscreen' : IDL.Null,
    'toner' : IDL.Null,
    'cleanser' : IDL.Null,
    'other' : IDL.Null,
    'serum' : IDL.Null,
    'moisturizer' : IDL.Null,
  });
  const Expense = IDL.Record({
    'date' : Time,
    'productName' : IDL.Text,
    'notes' : IDL.Text,
    'category' : ProductCategory,
    'amount' : IDL.Float64,
  });
  const ExpenseId = IDL.Nat;
  const JourneyEntry = IDL.Record({
    'breakoutsCount' : IDL.Nat,
    'hydrationLevel' : IDL.Nat,
    'date' : Time,
    'overallRating' : IDL.Nat,
    'notes' : IDL.Text,
    'skinCondition' : IDL.Text,
  });
  const JourneyEntryId = IDL.Nat;
  const Product = IDL.Record({
    'isFinished' : IDL.Bool,
    'purchasePrice' : IDL.Float64,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'category' : ProductCategory,
    'estimatedDays' : IDL.Nat,
    'startDate' : Time,
  });
  const ProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpense' : IDL.Func([Expense], [ExpenseId], []),
    'addJourneyEntry' : IDL.Func([JourneyEntry], [JourneyEntryId], []),
    'addProduct' : IDL.Func([Product], [ProductId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExpense' : IDL.Func([ExpenseId], [], []),
    'deleteJourneyEntry' : IDL.Func([JourneyEntryId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllJourneyEntries' : IDL.Func([], [IDL.Vec(JourneyEntry)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpense' : IDL.Func([ExpenseId], [Expense], ['query']),
    'getJourneyEntry' : IDL.Func([JourneyEntryId], [JourneyEntry], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getTotalExpenses' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateExpense' : IDL.Func([ExpenseId, Expense], [], []),
    'updateJourneyEntry' : IDL.Func([JourneyEntryId, JourneyEntry], [], []),
    'updateProduct' : IDL.Func([ProductId, Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };