/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Expense {
  'date' : Time,
  'productName' : string,
  'notes' : string,
  'category' : ProductCategory,
  'amount' : number,
}
export type ExpenseId = bigint;
export interface JourneyEntry {
  'breakoutsCount' : bigint,
  'hydrationLevel' : bigint,
  'date' : Time,
  'overallRating' : bigint,
  'notes' : string,
  'skinCondition' : string,
}
export type JourneyEntryId = bigint;
export interface Product {
  'isFinished' : boolean,
  'purchasePrice' : number,
  'name' : string,
  'notes' : string,
  'category' : ProductCategory,
  'estimatedDays' : bigint,
  'startDate' : Time,
}
export type ProductCategory = { 'sunscreen' : null } |
  { 'toner' : null } |
  { 'cleanser' : null } |
  { 'other' : null } |
  { 'serum' : null } |
  { 'moisturizer' : null };
export type ProductId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExpense' : ActorMethod<[Expense], ExpenseId>,
  'addJourneyEntry' : ActorMethod<[JourneyEntry], JourneyEntryId>,
  'addProduct' : ActorMethod<[Product], ProductId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteExpense' : ActorMethod<[ExpenseId], undefined>,
  'deleteJourneyEntry' : ActorMethod<[JourneyEntryId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllJourneyEntries' : ActorMethod<[], Array<JourneyEntry>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpense' : ActorMethod<[ExpenseId], Expense>,
  'getJourneyEntry' : ActorMethod<[JourneyEntryId], JourneyEntry>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getTotalExpenses' : ActorMethod<[], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateExpense' : ActorMethod<[ExpenseId, Expense], undefined>,
  'updateJourneyEntry' : ActorMethod<[JourneyEntryId, JourneyEntry], undefined>,
  'updateProduct' : ActorMethod<[ProductId, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];